<?php
/**
 * Implements hook_form_FORM_ID_alter
 */
function youth_misc_tweaks_form_user_register_form_alter(&$form, &$form_state) {
  drupal_set_title('Register Here to Become a Member');
  $form['civicrm-profile-register']['#weight'] = -11;
  $form['actions']['submit']['#value'] = 'Join Now';
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function youth_misc_tweaks_form_user_login_alter(&$form) {
  drupal_set_title('Register Here to Become a Member');
  $form['pass']['#description'] = 'If you forgot your password you can <a href="/user/password" title="Login without password">register without it here</a>.';
}

/**
 * Implements hook_menu_alter
 */
function youth_misc_tweaks_menu_alter(&$items){
  $items['user/register']['title'] = 'New member registration';
  $items['user/login']['title'] = 'Returning member registration';
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function youth_misc_tweaks_form_commerce_cart_add_to_cart_form_4_5_6_7_8_9_10_alter(&$form, &$form_state, &$form_id) {
  $form['submit']['#value'] = 'Sign up';
}

#function youth_misc_tweaks_form_alter(&$form, &$form_id) {
#  dpm($form_id);
#}

